### ISSUE TITLE
Package redshank-1.0.0 is unavailable

### ISSUE THREAD

**Issue by fluteguitar** [Wilfred/emacs-refactor#33]
Hello, 
I encounter this error ```Package redshank-1.0.0 is unavailable``` during installation from MELPA.
I did try to download a version of *redshank.el*, putting the source code file in *.emacs.d/*, then 
```require``` it in emacs init file successfully. But still, the error isnot fixed.
Could you give some hints to solve this issue?

**Comment by Wilfred** [comment]
redshank is available from MELPA, so you should be able to install it from there. What error are you getting after `(require 'redshank)`?

**Comment by fluteguitar** [comment]
After adding the following code to my init file, I could see redshank from package-list. 
```elisp
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
```
I thought this repo is already in my package-list, but it turn out that it did not.
