### ISSUE TITLE
Allow customizing key bindings

### ISSUE THREAD

**Issue by claxclinton** [Wilfred/emacs-refactor#49]
Hi,
Thanks for this wonderful tool!

Can the key bindings be customized or disabled?
The thing is that EMR interferes with my key bindings (C-c i).
I'm mainly using emr-show-refactor-menu.

Can you minimally add a customization to disable all EMR installed key bindings, I
would appreciate it.

Thanks,
Claes

**Comment by Wilfred** [comment]
Are you using EMR with C code? That's the only key binding I can see in all of EMR.

**Comment by claxclinton** [comment]
Yes, with C-Code.
