### ISSUE TITLE
Unexpected newline in `emr-el-extract-to-let`

### ISSUE THREAD

**Issue by symbiont-matthew-piziak** [Wilfred/emacs-refactor#52]
To reproduce, insert `(+ 1 (* 2 3))`, select `(* 2 3)`, and run `emr-el-extract-to-let`. This results in the following:
```
(let (
      (x (* 2 3)))
  (+ 1 x))
```

I would expect this instead:
```
(let ((x (* 2 3)))
  (+ 1 x))
```

This is only unsatisfying on the first variable extraction. Added variables work fine, since they are added to the body. If I start with this…
```
(let ((x (* 2 3)))
  (+ 1 x))
```
…and I extract `y = 1`, I get this…
```
(let ((x (* 2 3))
      (y 1))
  (+ y x))
```
…which looks good to me.

Is this behavior expected, can I fix it? Or is this something I should be customizing somewhere else?

**Comment by matthew-piziak** [comment]
Possible fix here? https://github.com/Wilfred/emacs-refactor/pull/53
