### ISSUE TITLE
Obsolete call to `emr-c-mode' in `emr-c-initialize'

### ISSUE THREAD

**Issue by Quiescent** [Wilfred/emacs-refactor#54]
It looks like when emr-c-mode was removed one call to it from `emr-c-initialize' was missed.  This causes the error: `File mode specification error: (void-function emr-c-mode)` when loading files which derive from `cc-mode'.

'm going to push a PR to remove this call momentarily.

**Comment by Quiescent** [comment]
PR: https://github.com/Wilfred/emacs-refactor/pull/55

**Comment by Wilfred** [comment]
Should be fixed now, thanks :)

**Comment by Quiescent** [comment]
Np.  And thank you! :tada:
